/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum ActionEnum {
    INCREASE, //TODO: Write general description for this element
    DECREASE; //TODO: Write general description for this element

    private static TreeMap<String, ActionEnum> valueMap = new TreeMap<String, ActionEnum>();
    private String value;

    static {
        INCREASE.value = "increase";
        DECREASE.value = "decrease";

        valueMap.put("increase", INCREASE);
        valueMap.put("decrease", DECREASE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ActionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ActionEnum values to list of string values
     * @param toConvert The list of ActionEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<ActionEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (ActionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 