/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class AddemailordomaintoSuppressionlistBuilder {
    //the instance to build
    private AddemailordomaintoSuppressionlist addemailordomaintoSuppressionlist;

    /**
     * Default constructor to initialize the instance
     */
    public AddemailordomaintoSuppressionlistBuilder() {
        addemailordomaintoSuppressionlist = new AddemailordomaintoSuppressionlist();
    }

    /**
     * Add the domain to be suppressed here. We will not deliver emails to recipients email addresses with this domain.<br>\nComma separate the values to suppress multiple domains..
     */
    public AddemailordomaintoSuppressionlistBuilder domain(String domain) {
        addemailordomaintoSuppressionlist.setDomain(domain);
        return this;
    }

    /**
     * Add an email address to be suppressed here. We will not deliver emails to this email address.<br>\nComma separate the values to suppress multiple email addresses
     */
    public AddemailordomaintoSuppressionlistBuilder email(String email) {
        addemailordomaintoSuppressionlist.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AddemailordomaintoSuppressionlist build() {
        return addemailordomaintoSuppressionlist;
    }
}