/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum AggregatedByEnum {
    DAY, //TODO: Write general description for this element
    WEEK, //TODO: Write general description for this element
    MONTH; //TODO: Write general description for this element

    private static TreeMap<String, AggregatedByEnum> valueMap = new TreeMap<String, AggregatedByEnum>();
    private String value;

    static {
        DAY.value = "day";
        WEEK.value = "week";
        MONTH.value = "month";

        valueMap.put("day", DAY);
        valueMap.put("week", WEEK);
        valueMap.put("month", MONTH);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static AggregatedByEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AggregatedByEnum values to list of string values
     * @param toConvert The list of AggregatedByEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<AggregatedByEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (AggregatedByEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 