/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class AttachmentsBuilder {
    //the instance to build
    private Attachments attachments;

    /**
     * Default constructor to initialize the instance
     */
    public AttachmentsBuilder() {
        attachments = new Attachments();
    }

    public AttachmentsBuilder fileContent(String fileContent) {
        attachments.setFileContent(fileContent);
        return this;
    }

    public AttachmentsBuilder fileName(String fileName) {
        attachments.setFileName(fileName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Attachments build() {
        return attachments;
    }
}