/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class AttachmentsBuilder {
    //the instance to build
    private Attachments attachments;

    /**
     * Default constructor to initialize the instance
     */
    public AttachmentsBuilder() {
        attachments = new Attachments();
    }

    /**
     * Base64 encoded value of the attached file
     */
    public AttachmentsBuilder content(String content) {
        attachments.setContent(content);
        return this;
    }

    /**
     * filename of attachments
     */
    public AttachmentsBuilder name(String name) {
        attachments.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Attachments build() {
        return attachments;
    }
}