/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class AttributeBuilder {
    //the instance to build
    private Attribute attribute;

    /**
     * Default constructor to initialize the instance
     */
    public AttributeBuilder() {
        attribute = new Attribute();
    }

    public AttributeBuilder myname(String myname) {
        attribute.setMyname(myname);
        return this;
    }

    public AttributeBuilder age(String age) {
        attribute.setAge(age);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Attribute build() {
        return attribute;
    }
}