/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Attribute 
        implements java.io.Serializable {
    private static final long serialVersionUID = -401645198716144096L;
    private String myname;
    private String age;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("myname")
    public String getMyname ( ) { 
        return this.myname;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("myname")
    public void setMyname (String value) { 
        this.myname = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("age")
    public String getAge ( ) { 
        return this.age;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("age")
    public void setAge (String value) { 
        this.age = value;
    }
 
}
 