/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Content 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1828743486665154052L;
    private TypeEnum type;
    private String value;
    /** GETTER
     * content in text/plain format
     */
    @JsonGetter("type")
    public TypeEnum getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * content in text/plain format
     */
    @JsonSetter("type")
    public void setType (TypeEnum value) { 
        this.type = value;
    }
 
    /** GETTER
     * HTML content to be sent in your email
     */
    @JsonGetter("value")
    public String getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * HTML content to be sent in your email
     */
    @JsonSetter("value")
    public void setValue (String value) { 
        this.value = value;
    }
 
}
