/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class DeleteDomainBuilder {
    //the instance to build
    private DeleteDomain deleteDomain;

    /**
     * Default constructor to initialize the instance
     */
    public DeleteDomainBuilder() {
        deleteDomain = new DeleteDomain();
    }

    /**
     * Name of the domain
     */
    public DeleteDomainBuilder domain(String domain) {
        deleteDomain.setDomain(domain);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeleteDomain build() {
        return deleteDomain;
    }
}