/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class DomainStructBuilder {
    //the instance to build
    private DomainStruct domainStruct;

    /**
     * Default constructor to initialize the instance
     */
    public DomainStructBuilder() {
        domainStruct = new DomainStruct();
    }

    /**
     * The domain you wish to include in the 'From' header of your emails.
     */
    public DomainStructBuilder domain(String domain) {
        domainStruct.setDomain(domain);
        return this;
    }

    /**
     * The subdomain which will be used for tracking opens, clicks and unsubscribe
     */
    public DomainStructBuilder envelopeName(String envelopeName) {
        domainStruct.setEnvelopeName(envelopeName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DomainStruct build() {
        return domainStruct;
    }
}