/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DomainStruct 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2005042222058852096L;
    private String domain;
    private String envelopeName;
    /** GETTER
     * The domain you wish to include in the 'From' header of your emails.
     */
    @JsonGetter("domain")
    public String getDomain ( ) { 
        return this.domain;
    }
    
    /** SETTER
     * The domain you wish to include in the 'From' header of your emails.
     */
    @JsonSetter("domain")
    public void setDomain (String value) { 
        this.domain = value;
    }
 
    /** GETTER
     * The subdomain which will be used for tracking opens, clicks and unsubscribe
     */
    @JsonGetter("envelopeName")
    public String getEnvelopeName ( ) { 
        return this.envelopeName;
    }
    
    /** SETTER
     * The subdomain which will be used for tracking opens, clicks and unsubscribe
     */
    @JsonSetter("envelopeName")
    public void setEnvelopeName (String value) { 
        this.envelopeName = value;
    }
 
}
