/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class EmailBodyAttachments 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1809495909420244490L;
    private String fileContent;
    private String fileName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileContent")
    public String getFileContent ( ) { 
        return this.fileContent;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileContent")
    public void setFileContent (String value) { 
        this.fileContent = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileName")
    public String getFileName ( ) { 
        return this.fileName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileName")
    public void setFileName (String value) { 
        this.fileName = value;
    }
 
}
 