/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class EmailBodyBuilder {
    //the instance to build
    private EmailBody emailBody;

    /**
     * Default constructor to initialize the instance
     */
    public EmailBodyBuilder() {
        emailBody = new EmailBody();
    }

    public EmailBodyBuilder personalizations(List<Personalizations> personalizations) {
        emailBody.setPersonalizations(personalizations);
        return this;
    }

    public EmailBodyBuilder tags(String tags) {
        emailBody.setTags(tags);
        return this;
    }

    public EmailBodyBuilder from(From from) {
        emailBody.setFrom(from);
        return this;
    }

    public EmailBodyBuilder subject(String subject) {
        emailBody.setSubject(subject);
        return this;
    }

    public EmailBodyBuilder content(String content) {
        emailBody.setContent(content);
        return this;
    }

    public EmailBodyBuilder attachments(List<EmailBodyAttachments> attachments) {
        emailBody.setAttachments(attachments);
        return this;
    }

    public EmailBodyBuilder settings(Settings settings) {
        emailBody.setSettings(settings);
        return this;
    }

    public EmailBodyBuilder replyToId(String replyToId) {
        emailBody.setReplyToId(replyToId);
        return this;
    }

    public EmailBodyBuilder templateId(Integer templateId) {
        emailBody.setTemplateId(templateId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EmailBody build() {
        return emailBody;
    }
}