/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class EmailBody 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8339168689734442111L;
    private List<Personalizations> personalizations;
    private String tags;
    private From from;
    private String subject;
    private String content;
    private List<EmailBodyAttachments> attachments;
    private Settings settings;
    private String replyToId;
    private Integer templateId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("personalizations")
    public List<Personalizations> getPersonalizations ( ) { 
        return this.personalizations;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("personalizations")
    public void setPersonalizations (List<Personalizations> value) { 
        this.personalizations = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tags")
    public String getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tags")
    public void setTags (String value) { 
        this.tags = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("from")
    public From getFrom ( ) { 
        return this.from;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("from")
    public void setFrom (From value) { 
        this.from = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subject")
    public String getSubject ( ) { 
        return this.subject;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subject")
    public void setSubject (String value) { 
        this.subject = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("content")
    public String getContent ( ) { 
        return this.content;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("content")
    public void setContent (String value) { 
        this.content = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attachments")
    public List<EmailBodyAttachments> getAttachments ( ) { 
        return this.attachments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attachments")
    public void setAttachments (List<EmailBodyAttachments> value) { 
        this.attachments = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("settings")
    public Settings getSettings ( ) { 
        return this.settings;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("settings")
    public void setSettings (Settings value) { 
        this.settings = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("replyToId")
    public String getReplyToId ( ) { 
        return this.replyToId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("replyToId")
    public void setReplyToId (String value) { 
        this.replyToId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("templateId")
    public Integer getTemplateId ( ) { 
        return this.templateId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("templateId")
    public void setTemplateId (Integer value) { 
        this.templateId = value;
    }
 
}
 