/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class EnableordisablesubacoountBuilder {
    //the instance to build
    private Enableordisablesubacoount enableordisablesubacoount;

    /**
     * Default constructor to initialize the instance
     */
    public EnableordisablesubacoountBuilder() {
        enableordisablesubacoount = new Enableordisablesubacoount();
    }

    /**
     * The username of the subaccount
     */
    public EnableordisablesubacoountBuilder username(String username) {
        enableordisablesubacoount.setUsername(username);
        return this;
    }

    /**
     * Flag to indicate whether the subaccount should be enabled or disabled.
     */
    public EnableordisablesubacoountBuilder disabled(Boolean disabled) {
        enableordisablesubacoount.setDisabled(disabled);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Enableordisablesubacoount build() {
        return enableordisablesubacoount;
    }
}