/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class EnableOrDisableSubacoountBuilder {
    //the instance to build
    private EnableOrDisableSubacoount enableOrDisableSubacoount;

    /**
     * Default constructor to initialize the instance
     */
    public EnableOrDisableSubacoountBuilder() {
        enableOrDisableSubacoount = new EnableOrDisableSubacoount();
    }

    /**
     * The username of the subaccount
     */
    public EnableOrDisableSubacoountBuilder username(String username) {
        enableOrDisableSubacoount.setUsername(username);
        return this;
    }

    /**
     * Flag to indicate whether the subaccount should be enabled or disabled.
     */
    public EnableOrDisableSubacoountBuilder disabled(Boolean disabled) {
        enableOrDisableSubacoount.setDisabled(disabled);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EnableOrDisableSubacoount build() {
        return enableOrDisableSubacoount;
    }
}