/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class From 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3373572935892553842L;
    private String fromEmail;
    private String fromName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fromEmail")
    public String getFromEmail ( ) { 
        return this.fromEmail;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fromEmail")
    public void setFromEmail (String value) { 
        this.fromEmail = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fromName")
    public String getFromName ( ) { 
        return this.fromName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fromName")
    public void setFromName (String value) { 
        this.fromName = value;
    }
 
}
 