/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class FromBuilder {
    //the instance to build
    private From from;

    /**
     * Default constructor to initialize the instance
     */
    public FromBuilder() {
        from = new From();
    }

    public FromBuilder fromEmail(String fromEmail) {
        from.setFromEmail(fromEmail);
        return this;
    }

    public FromBuilder fromName(String fromName) {
        from.setFromName(fromName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public From build() {
        return from;
    }
}