/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Personalizations 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5418571806540860635L;
    private Object attributes;
    private Object headers;
    private List<Attachments> attachments;
    private List<EmailStruct> to;
    private List<EmailStruct> cc;
    private List<EmailStruct> bcc;
    private String tokenTo;
    private String tokenCc;
    private String tokenBcc;
    /** GETTER
     * Dynamic attributes
     */
    @JsonGetter("attributes")
    public Object getAttributes ( ) { 
        return this.attributes;
    }
    
    /** SETTER
     * Dynamic attributes
     */
    @JsonSetter("attributes")
    public void setAttributes (Object value) { 
        this.attributes = value;
    }
 
    /** GETTER
     * Dynamic headers attributes
     */
    @JsonGetter("headers")
    public Object getHeaders ( ) { 
        return this.headers;
    }
    
    /** SETTER
     * Dynamic headers attributes
     */
    @JsonSetter("headers")
    public void setHeaders (Object value) { 
        this.headers = value;
    }
 
    /** GETTER
     * Attachments to individuals recipient
     */
    @JsonGetter("attachments")
    public List<Attachments> getAttachments ( ) { 
        return this.attachments;
    }
    
    /** SETTER
     * Attachments to individuals recipient
     */
    @JsonSetter("attachments")
    public void setAttachments (List<Attachments> value) { 
        this.attachments = value;
    }
 
    /** GETTER
     * To email-address
     */
    @JsonGetter("to")
    public List<EmailStruct> getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * To email-address
     */
    @JsonSetter("to")
    public void setTo (List<EmailStruct> value) { 
        this.to = value;
    }
 
    /** GETTER
     * CC email-address
     */
    @JsonGetter("cc")
    public List<EmailStruct> getCc ( ) { 
        return this.cc;
    }
    
    /** SETTER
     * CC email-address
     */
    @JsonSetter("cc")
    public void setCc (List<EmailStruct> value) { 
        this.cc = value;
    }
 
    /** GETTER
     * Bcc email-addresses
     */
    @JsonGetter("bcc")
    public List<EmailStruct> getBcc ( ) { 
        return this.bcc;
    }
    
    /** SETTER
     * Bcc email-addresses
     */
    @JsonSetter("bcc")
    public void setBcc (List<EmailStruct> value) { 
        this.bcc = value;
    }
 
    /** GETTER
     * token to which is json string
     */
    @JsonGetter("token_to")
    public String getTokenTo ( ) { 
        return this.tokenTo;
    }
    
    /** SETTER
     * token to which is json string
     */
    @JsonSetter("token_to")
    public void setTokenTo (String value) { 
        this.tokenTo = value;
    }
 
    /** GETTER
     * token cc which is json string
     */
    @JsonGetter("token_cc")
    public String getTokenCc ( ) { 
        return this.tokenCc;
    }
    
    /** SETTER
     * token cc which is json string
     */
    @JsonSetter("token_cc")
    public void setTokenCc (String value) { 
        this.tokenCc = value;
    }
 
    /** GETTER
     * token bcc which is json string
     */
    @JsonGetter("token_bcc")
    public String getTokenBcc ( ) { 
        return this.tokenBcc;
    }
    
    /** SETTER
     * token bcc which is json string
     */
    @JsonSetter("token_bcc")
    public void setTokenBcc (String value) { 
        this.tokenBcc = value;
    }
 
}
