/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Personalizations 
        implements java.io.Serializable {
    private static final long serialVersionUID = 123272188473706523L;
    private String recipient;
    private String xApiheaderCc;
    private String xApiheader;
    private Object attributes;
    private List<Attachments> attachments;
    private List<String> recipientCc;
    /** GETTER
     * Emails to be passed in Apicall
     */
    @JsonGetter("recipient")
    public String getRecipient ( ) { 
        return this.recipient;
    }
    
    /** SETTER
     * Emails to be passed in Apicall
     */
    @JsonSetter("recipient")
    public void setRecipient (String value) { 
        this.recipient = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("x-apiheader_cc")
    public String getXApiheaderCc ( ) { 
        return this.xApiheaderCc;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("x-apiheader_cc")
    public void setXApiheaderCc (String value) { 
        this.xApiheaderCc = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("x-apiheader")
    public String getXApiheader ( ) { 
        return this.xApiheader;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("x-apiheader")
    public void setXApiheader (String value) { 
        this.xApiheader = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attributes")
    public Object getAttributes ( ) { 
        return this.attributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attributes")
    public void setAttributes (Object value) { 
        this.attributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attachments")
    public List<Attachments> getAttachments ( ) { 
        return this.attachments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attachments")
    public void setAttachments (List<Attachments> value) { 
        this.attachments = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("recipient_cc")
    public List<String> getRecipientCc ( ) { 
        return this.recipientCc;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("recipient_cc")
    public void setRecipientCc (List<String> value) { 
        this.recipientCc = value;
    }
 
}
 