/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class RemoveEmailOrDomainToSuppressionListBuilder {
    //the instance to build
    private RemoveEmailOrDomainToSuppressionList removeEmailOrDomainToSuppressionList;

    /**
     * Default constructor to initialize the instance
     */
    public RemoveEmailOrDomainToSuppressionListBuilder() {
        removeEmailOrDomainToSuppressionList = new RemoveEmailOrDomainToSuppressionList();
    }

    /**
     * List one or more recipient domains to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple recipient domains.
     */
    public RemoveEmailOrDomainToSuppressionListBuilder domain(String domain) {
        removeEmailOrDomainToSuppressionList.setDomain(domain);
        return this;
    }

    /**
     * List one or more email addresses to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple email addresses.
     */
    public RemoveEmailOrDomainToSuppressionListBuilder email(String email) {
        removeEmailOrDomainToSuppressionList.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RemoveEmailOrDomainToSuppressionList build() {
        return removeEmailOrDomainToSuppressionList;
    }
}