/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class RemoveemailordomaintoSuppressionlist 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4584649771901417522L;
    private String domain;
    private String email;
    /** GETTER
     * List one or more recipient domains to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple recipient domains.
     */
    @JsonGetter("domain")
    public String getDomain ( ) { 
        return this.domain;
    }
    
    /** SETTER
     * List one or more recipient domains to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple recipient domains.
     */
    @JsonSetter("domain")
    public void setDomain (String value) { 
        this.domain = value;
    }
 
    /** GETTER
     * List one or more email addresses to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple email addresses.
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * List one or more email addresses to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple email addresses.
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
}
