/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class RemoveemailordomaintoSuppressionlistBuilder {
    //the instance to build
    private RemoveemailordomaintoSuppressionlist removeemailordomaintoSuppressionlist;

    /**
     * Default constructor to initialize the instance
     */
    public RemoveemailordomaintoSuppressionlistBuilder() {
        removeemailordomaintoSuppressionlist = new RemoveemailordomaintoSuppressionlist();
    }

    /**
     * List one or more recipient domains to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple recipient domains.
     */
    public RemoveemailordomaintoSuppressionlistBuilder domain(String domain) {
        removeemailordomaintoSuppressionlist.setDomain(domain);
        return this;
    }

    /**
     * List one or more email addresses to be removed from the suppression list here. <br>\nComma separate the values to suppress multiple email addresses.
     */
    public RemoveemailordomaintoSuppressionlistBuilder email(String email) {
        removeemailordomaintoSuppressionlist.setEmail(email);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RemoveemailordomaintoSuppressionlist build() {
        return removeemailordomaintoSuppressionlist;
    }
}