/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class SendEmailResponseBuilder {
    //the instance to build
    private SendEmailResponse sendEmailResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SendEmailResponseBuilder() {
        sendEmailResponse = new SendEmailResponse();
    }

    public SendEmailResponseBuilder data(Object data) {
        sendEmailResponse.setData(data);
        return this;
    }

    public SendEmailResponseBuilder errorInfo(SendEmailError errorInfo) {
        sendEmailResponse.setErrorInfo(errorInfo);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SendEmailResponse build() {
        return sendEmailResponse;
    }
}