/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendEmailResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4221350437312414359L;
    private Object data;
    private String message;
    private SendEmailError errorInfo;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public Object getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (Object value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("message")
    private void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("error_info")
    public SendEmailError getErrorInfo ( ) { 
        return this.errorInfo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("error_info")
    public void setErrorInfo (SendEmailError value) { 
        this.errorInfo = value;
    }
 
}
 