/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendEmailError 
        implements java.io.Serializable {
    private static final long serialVersionUID = -7638280116293860302L;
    private String errorMessage;
    private int errorCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("error_message")
    public String getErrorMessage ( ) { 
        return this.errorMessage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("error_message")
    public void setErrorMessage (String value) { 
        this.errorMessage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("error_code")
    public int getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("error_code")
    public void setErrorCode (int value) { 
        this.errorCode = value;
    }
 
}
 