/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class SendEmailErrorBuilder {
    //the instance to build
    private SendEmailError sendEmailError;

    /**
     * Default constructor to initialize the instance
     */
    public SendEmailErrorBuilder() {
        sendEmailError = new SendEmailError();
    }

    public SendEmailErrorBuilder errorMessage(String errorMessage) {
        sendEmailError.setErrorMessage(errorMessage);
        return this;
    }

    public SendEmailErrorBuilder errorCode(int errorCode) {
        sendEmailError.setErrorCode(errorCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SendEmailError build() {
        return sendEmailError;
    }
}