/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class SettingsBuilder {
    //the instance to build
    private Settings settings;

    /**
     * Default constructor to initialize the instance
     */
    public SettingsBuilder() {
        settings = new Settings();
    }

    public SettingsBuilder footer(Integer footer) {
        settings.setFooter(footer);
        return this;
    }

    public SettingsBuilder clicktrack(Integer clicktrack) {
        settings.setClicktrack(clicktrack);
        return this;
    }

    public SettingsBuilder opentrack(Integer opentrack) {
        settings.setOpentrack(opentrack);
        return this;
    }

    public SettingsBuilder unsubscribe(Integer unsubscribe) {
        settings.setUnsubscribe(unsubscribe);
        return this;
    }

    public SettingsBuilder bcc(String bcc) {
        settings.setBcc(bcc);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Settings build() {
        return settings;
    }
}