/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Settings 
        implements java.io.Serializable {
    private static final long serialVersionUID = -7260395336814054371L;
    private Boolean footer;
    private Boolean clickTrack;
    private Boolean openTrack;
    private Boolean unsubscribeTrack;
    private Boolean hepf;
    /** GETTER
     * enable or disable footer
     */
    @JsonGetter("footer")
    public Boolean getFooter ( ) { 
        return this.footer;
    }
    
    /** SETTER
     * enable or disable footer
     */
    @JsonSetter("footer")
    public void setFooter (Boolean value) { 
        this.footer = value;
    }
 
    /** GETTER
     * enable or disable click tracking
     */
    @JsonGetter("click_track")
    public Boolean getClickTrack ( ) { 
        return this.clickTrack;
    }
    
    /** SETTER
     * enable or disable click tracking
     */
    @JsonSetter("click_track")
    public void setClickTrack (Boolean value) { 
        this.clickTrack = value;
    }
 
    /** GETTER
     * enable or disable open tracking
     */
    @JsonGetter("open_track")
    public Boolean getOpenTrack ( ) { 
        return this.openTrack;
    }
    
    /** SETTER
     * enable or disable open tracking
     */
    @JsonSetter("open_track")
    public void setOpenTrack (Boolean value) { 
        this.openTrack = value;
    }
 
    /** GETTER
     * enable or disable unsubscribe tracking
     */
    @JsonGetter("unsubscribe_track")
    public Boolean getUnsubscribeTrack ( ) { 
        return this.unsubscribeTrack;
    }
    
    /** SETTER
     * enable or disable unsubscribe tracking
     */
    @JsonSetter("unsubscribe_track")
    public void setUnsubscribeTrack (Boolean value) { 
        this.unsubscribeTrack = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hepf")
    public Boolean getHepf ( ) { 
        return this.hepf;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hepf")
    public void setHepf (Boolean value) { 
        this.hepf = value;
    }
 
}
