/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Settings 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8009324548759081864L;
    private Integer footer;
    private Integer clicktrack;
    private Integer opentrack;
    private Integer unsubscribe;
    private String bcc;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("footer")
    public Integer getFooter ( ) { 
        return this.footer;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("footer")
    public void setFooter (Integer value) { 
        this.footer = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("clicktrack")
    public Integer getClicktrack ( ) { 
        return this.clicktrack;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("clicktrack")
    public void setClicktrack (Integer value) { 
        this.clicktrack = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("opentrack")
    public Integer getOpentrack ( ) { 
        return this.opentrack;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("opentrack")
    public void setOpentrack (Integer value) { 
        this.opentrack = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("unsubscribe")
    public Integer getUnsubscribe ( ) { 
        return this.unsubscribe;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("unsubscribe")
    public void setUnsubscribe (Integer value) { 
        this.unsubscribe = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bcc")
    public String getBcc ( ) { 
        return this.bcc;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bcc")
    public void setBcc (String value) { 
        this.bcc = value;
    }
 
}
 