/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class UpdaterecurringCredisofsubaccount 
        implements java.io.Serializable {
    private static final long serialVersionUID = 592320434528661119L;
    private String username;
    private Integer recurringCredit;
    private TimeperiodEnum timeperiod;
    private String startDate;
    private String endDate;
    private String status;
    /** GETTER
     * The username of the subaccount
     */
    @JsonGetter("username")
    public String getUsername ( ) { 
        return this.username;
    }
    
    /** SETTER
     * The username of the subaccount
     */
    @JsonSetter("username")
    public void setUsername (String value) { 
        this.username = value;
    }
 
    /** GETTER
     * The amount to be added periodically
     */
    @JsonGetter("recurring_credit")
    public Integer getRecurringCredit ( ) { 
        return this.recurringCredit;
    }
    
    /** SETTER
     * The amount to be added periodically
     */
    @JsonSetter("recurring_credit")
    public void setRecurringCredit (Integer value) { 
        this.recurringCredit = value;
    }
 
    /** GETTER
     * The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
     */
    @JsonGetter("timeperiod")
    public TimeperiodEnum getTimeperiod ( ) { 
        return this.timeperiod;
    }
    
    /** SETTER
     * The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
     */
    @JsonSetter("timeperiod")
    public void setTimeperiod (TimeperiodEnum value) { 
        this.timeperiod = value;
    }
 
    /** GETTER
     * The date from which the credit allocation will commence
     */
    @JsonGetter("start_date")
    public String getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * The date from which the credit allocation will commence
     */
    @JsonSetter("start_date")
    public void setStartDate (String value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * The last date of credit allocation
     */
    @JsonGetter("end_date")
    public String getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * The last date of credit allocation
     */
    @JsonSetter("end_date")
    public void setEndDate (String value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * Flag to enable or disable the recurring credit allocation
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Flag to enable or disable the recurring credit allocation
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
}
