/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdateCredisOfSubaccountBuilder {
    //the instance to build
    private UpdateCredisOfSubaccount updateCredisOfSubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateCredisOfSubaccountBuilder() {
        updateCredisOfSubaccount = new UpdateCredisOfSubaccount();
    }

    /**
     * The username of the subaccount
     */
    public UpdateCredisOfSubaccountBuilder username(String username) {
        updateCredisOfSubaccount.setUsername(username);
        return this;
    }

    /**
     * Indicate the action (add or subtract) to be taken.Allowed values increase, decrease
     */
    public UpdateCredisOfSubaccountBuilder action(ActionEnum action) {
        updateCredisOfSubaccount.setAction(action);
        return this;
    }

    /**
     * Amount of credits
     */
    public UpdateCredisOfSubaccountBuilder amount(Integer amount) {
        updateCredisOfSubaccount.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateCredisOfSubaccount build() {
        return updateCredisOfSubaccount;
    }
}