/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdateRecurringCredisOfSubaccountBuilder {
    //the instance to build
    private UpdateRecurringCredisOfSubaccount updateRecurringCredisOfSubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateRecurringCredisOfSubaccountBuilder() {
        updateRecurringCredisOfSubaccount = new UpdateRecurringCredisOfSubaccount();
    }

    /**
     * The username of the subaccount
     */
    public UpdateRecurringCredisOfSubaccountBuilder username(String username) {
        updateRecurringCredisOfSubaccount.setUsername(username);
        return this;
    }

    /**
     * The amount to be added periodically
     */
    public UpdateRecurringCredisOfSubaccountBuilder recurringCredit(Integer recurringCredit) {
        updateRecurringCredisOfSubaccount.setRecurringCredit(recurringCredit);
        return this;
    }

    /**
     * The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
     */
    public UpdateRecurringCredisOfSubaccountBuilder timeperiod(TimeperiodEnum timeperiod) {
        updateRecurringCredisOfSubaccount.setTimeperiod(timeperiod);
        return this;
    }

    /**
     * The date from which the credit allocation will commence
     */
    public UpdateRecurringCredisOfSubaccountBuilder startDate(String startDate) {
        updateRecurringCredisOfSubaccount.setStartDate(startDate);
        return this;
    }

    /**
     * The last date of credit allocation
     */
    public UpdateRecurringCredisOfSubaccountBuilder endDate(String endDate) {
        updateRecurringCredisOfSubaccount.setEndDate(endDate);
        return this;
    }

    /**
     * Flag to enable or disable the recurring credit allocation
     */
    public UpdateRecurringCredisOfSubaccountBuilder status(String status) {
        updateRecurringCredisOfSubaccount.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateRecurringCredisOfSubaccount build() {
        return updateRecurringCredisOfSubaccount;
    }
}