/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdateCredisofsubaccountBuilder {
    //the instance to build
    private UpdateCredisofsubaccount updateCredisofsubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateCredisofsubaccountBuilder() {
        updateCredisofsubaccount = new UpdateCredisofsubaccount();
    }

    /**
     * The username of the subaccount
     */
    public UpdateCredisofsubaccountBuilder username(String username) {
        updateCredisofsubaccount.setUsername(username);
        return this;
    }

    /**
     * Indicate the action (add or subtract) to be taken.Allowed values increase, decrease
     */
    public UpdateCredisofsubaccountBuilder action(ActionEnum action) {
        updateCredisofsubaccount.setAction(action);
        return this;
    }

    /**
     * Amount of credits
     */
    public UpdateCredisofsubaccountBuilder amount(Integer amount) {
        updateCredisofsubaccount.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateCredisofsubaccount build() {
        return updateCredisofsubaccount;
    }
}