/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdatesubaccountBuilder {
    //the instance to build
    private Updatesubaccount updatesubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdatesubaccountBuilder() {
        updatesubaccount = new Updatesubaccount();
    }

    /**
     * The username for the subaccount
     */
    public UpdatesubaccountBuilder username(String username) {
        updatesubaccount.setUsername(username);
        return this;
    }

    /**
     * The new email address to be registered with the subaccount
     */
    public UpdatesubaccountBuilder newEmail(String newEmail) {
        updatesubaccount.setNewEmail(newEmail);
        return this;
    }

    /**
     * The new password of the subaccount
     */
    public UpdatesubaccountBuilder newPassword(String newPassword) {
        updatesubaccount.setNewPassword(newPassword);
        return this;
    }

    /**
     * reconfirm the new password for the subaccount
     */
    public UpdatesubaccountBuilder confirmPassword(String confirmPassword) {
        updatesubaccount.setConfirmPassword(confirmPassword);
        return this;
    }

    /**
     * Allowed values one_time_credit or unlimited by default, all subaccounts are created with credit type as unlimited.
     */
    public UpdatesubaccountBuilder creditType(String creditType) {
        updatesubaccount.setCreditType(creditType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Updatesubaccount build() {
        return updatesubaccount;
    }
}