/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Updatesubaccount 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4804075073457079350L;
    private String username;
    private String newEmail;
    private String newPassword;
    private String confirmPassword;
    private String creditType;
    /** GETTER
     * The username for the subaccount
     */
    @JsonGetter("username")
    public String getUsername ( ) { 
        return this.username;
    }
    
    /** SETTER
     * The username for the subaccount
     */
    @JsonSetter("username")
    public void setUsername (String value) { 
        this.username = value;
    }
 
    /** GETTER
     * The new email address to be registered with the subaccount
     */
    @JsonGetter("new_email")
    public String getNewEmail ( ) { 
        return this.newEmail;
    }
    
    /** SETTER
     * The new email address to be registered with the subaccount
     */
    @JsonSetter("new_email")
    public void setNewEmail (String value) { 
        this.newEmail = value;
    }
 
    /** GETTER
     * The new password of the subaccount
     */
    @JsonGetter("new_password")
    public String getNewPassword ( ) { 
        return this.newPassword;
    }
    
    /** SETTER
     * The new password of the subaccount
     */
    @JsonSetter("new_password")
    public void setNewPassword (String value) { 
        this.newPassword = value;
    }
 
    /** GETTER
     * reconfirm the new password for the subaccount
     */
    @JsonGetter("confirm_password")
    public String getConfirmPassword ( ) { 
        return this.confirmPassword;
    }
    
    /** SETTER
     * reconfirm the new password for the subaccount
     */
    @JsonSetter("confirm_password")
    public void setConfirmPassword (String value) { 
        this.confirmPassword = value;
    }
 
    /** GETTER
     * Allowed values one_time_credit or unlimited by default, all subaccounts are created with credit type as unlimited.
     */
    @JsonGetter("credit_type")
    public String getCreditType ( ) { 
        return this.creditType;
    }
    
    /** SETTER
     * Allowed values one_time_credit or unlimited by default, all subaccounts are created with credit type as unlimited.
     */
    @JsonSetter("credit_type")
    public void setCreditType (String value) { 
        this.creditType = value;
    }
 
}
