/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdaterecurringCredisofsubaccountBuilder {
    //the instance to build
    private UpdaterecurringCredisofsubaccount updaterecurringCredisofsubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdaterecurringCredisofsubaccountBuilder() {
        updaterecurringCredisofsubaccount = new UpdaterecurringCredisofsubaccount();
    }

    /**
     * The username of the subaccount
     */
    public UpdaterecurringCredisofsubaccountBuilder username(String username) {
        updaterecurringCredisofsubaccount.setUsername(username);
        return this;
    }

    /**
     * The amount to be added periodically
     */
    public UpdaterecurringCredisofsubaccountBuilder recurringCredit(Integer recurringCredit) {
        updaterecurringCredisofsubaccount.setRecurringCredit(recurringCredit);
        return this;
    }

    /**
     * The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
     */
    public UpdaterecurringCredisofsubaccountBuilder timeperiod(TimeperiodEnum timeperiod) {
        updaterecurringCredisofsubaccount.setTimeperiod(timeperiod);
        return this;
    }

    /**
     * The date from which the credit allocation will commence
     */
    public UpdaterecurringCredisofsubaccountBuilder startDate(String startDate) {
        updaterecurringCredisofsubaccount.setStartDate(startDate);
        return this;
    }

    /**
     * The last date of credit allocation
     */
    public UpdaterecurringCredisofsubaccountBuilder endDate(String endDate) {
        updaterecurringCredisofsubaccount.setEndDate(endDate);
        return this;
    }

    /**
     * Flag to enable or disable the recurring credit allocation
     */
    public UpdaterecurringCredisofsubaccountBuilder status(String status) {
        updaterecurringCredisofsubaccount.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdaterecurringCredisofsubaccount build() {
        return updaterecurringCredisofsubaccount;
    }
}