/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api.models;

import java.util.*;

public class UpdateSubaccountBuilder {
    //the instance to build
    private UpdateSubaccount updateSubaccount;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSubaccountBuilder() {
        updateSubaccount = new UpdateSubaccount();
    }

    /**
     * The username for the subaccount
     */
    public UpdateSubaccountBuilder username(String username) {
        updateSubaccount.setUsername(username);
        return this;
    }

    /**
     * The new email address to be registered with the subaccount
     */
    public UpdateSubaccountBuilder newEmail(String newEmail) {
        updateSubaccount.setNewEmail(newEmail);
        return this;
    }

    /**
     * The new password of the subaccount
     */
    public UpdateSubaccountBuilder newPassword(String newPassword) {
        updateSubaccount.setNewPassword(newPassword);
        return this;
    }

    /**
     * reconfirm the new password for the subaccount
     */
    public UpdateSubaccountBuilder confirmPassword(String confirmPassword) {
        updateSubaccount.setConfirmPassword(confirmPassword);
        return this;
    }

    /**
     * Allowed values one_time_credit or unlimited by default, all subaccounts are created with credit type as unlimited.
     */
    public UpdateSubaccountBuilder creditType(String creditType) {
        updateSubaccount.setCreditType(creditType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSubaccount build() {
        return updateSubaccount;
    }
}