/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://api.pepipost.com";

}
