/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api;

import com.pepipost.api.controllers.*;
import com.pepipost.api.http.client.HttpClient;

public class PepipostClient {
    /**
     * Singleton access to Send controller
     * @return	Returns the SendController instance 
     */
    public SendController getSend() {
        return SendController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public PepipostClient() {
        Configuration.apiKey = "4D51B3ECA2D4ED3A67E4E043B3F1A4D1";
    }

    /**
     * Client initialization constructor 
     */     
    public PepipostClient(String apiKey) {
        this();
        if(apiKey != null) Configuration.apiKey = apiKey;
    }
}