/*
 * PepipostLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.pepipost.api;

import com.pepipost.api.controllers.*;
import com.pepipost.api.http.client.HttpClient;

public class PepipostClient {
    /**
     * Singleton access to Email controller
     * @return	Returns the EmailController instance 
     */
    public EmailController getEmail() {
        return EmailController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public PepipostClient() {
    }

}