/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Attributes
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T12:18:50.368Z")
public class Attributes   {
  @SerializedName("NAME")
  private List<String> NAME = new ArrayList<String>();

  @SerializedName("REGID")
  private List<String> REGID = new ArrayList<String>();

  public Attributes NAME(List<String> NAME) {
    this.NAME = NAME;
    return this;
  }

  public Attributes addNAMEItem(String NAMEItem) {
    this.NAME.add(NAMEItem);
    return this;
  }

   /**
   * Get NAME
   * @return NAME
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNAME() {
    return NAME;
  }

  public void setNAME(List<String> NAME) {
    this.NAME = NAME;
  }

  public Attributes REGID(List<String> REGID) {
    this.REGID = REGID;
    return this;
  }

  public Attributes addREGIDItem(String REGIDItem) {
    this.REGID.add(REGIDItem);
    return this;
  }

   /**
   * Get REGID
   * @return REGID
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getREGID() {
    return REGID;
  }

  public void setREGID(List<String> REGID) {
    this.REGID = REGID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attributes attributes = (Attributes) o;
    return Objects.equals(this.NAME, attributes.NAME) &&
        Objects.equals(this.REGID, attributes.REGID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(NAME, REGID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attributes {\n");
    
    sb.append("    NAME: ").append(toIndentedString(NAME)).append("\n");
    sb.append("    REGID: ").append(toIndentedString(REGID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

