/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * EmailDetails
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T12:18:50.368Z")
public class EmailDetails   {
  @SerializedName("fromname")
  private String fromname = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("from")
  private String from = null;

  @SerializedName("replytoid")
  private String replytoid = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("content")
  private String content = null;

  public EmailDetails fromname(String fromname) {
    this.fromname = fromname;
    return this;
  }

   /**
   * Get fromname
   * @return fromname
  **/
  @ApiModelProperty(example = "sender name", value = "")
  public String getFromname() {
    return fromname;
  }

  public void setFromname(String fromname) {
    this.fromname = fromname;
  }

  public EmailDetails subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(example = "Hi [%NAME%], This is a test email subject", value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public EmailDetails from(String from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(example = "from@example.com", value = "")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public EmailDetails replytoid(String replytoid) {
    this.replytoid = replytoid;
    return this;
  }

   /**
   * Get replytoid
   * @return replytoid
  **/
  @ApiModelProperty(example = "replyto@example.com", value = "")
  public String getReplytoid() {
    return replytoid;
  }

  public void setReplytoid(String replytoid) {
    this.replytoid = replytoid;
  }

  public EmailDetails tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "AccountDeactivation, Verification", value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public EmailDetails content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "&lt;p&gt;hi [% NAME %],&lt;/p&gt;&lt;p&gt;This is a test email sent using Pepipost API&lt;/p&gt;", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailDetails emailDetails = (EmailDetails) o;
    return Objects.equals(this.fromname, emailDetails.fromname) &&
        Objects.equals(this.subject, emailDetails.subject) &&
        Objects.equals(this.from, emailDetails.from) &&
        Objects.equals(this.replytoid, emailDetails.replytoid) &&
        Objects.equals(this.tags, emailDetails.tags) &&
        Objects.equals(this.content, emailDetails.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromname, subject, from, replytoid, tags, content);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailDetails {\n");
    
    sb.append("    fromname: ").append(toIndentedString(fromname)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    replytoid: ").append(toIndentedString(replytoid)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

