/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Attributes;
import io.swagger.client.model.EmailDetails;
import io.swagger.client.model.Files;
import io.swagger.client.model.Settings;
import java.util.ArrayList;
import java.util.List;


/**
 * Emailv1
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T12:18:50.368Z")
public class Emailv1   {
  @SerializedName("api_key")
  private String apiKey = null;

  @SerializedName("email_details")
  private EmailDetails emailDetails = null;

  @SerializedName("X-APIHEADER")
  private List<String> X_APIHEADER = new ArrayList<String>();

  @SerializedName("settings")
  private Settings settings = null;

  @SerializedName("recipients")
  private List<String> recipients = new ArrayList<String>();

  @SerializedName("attributes")
  private Attributes attributes = null;

  @SerializedName("files")
  private Files files = null;

  public Emailv1 apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Your secret API Key
   * @return apiKey
  **/
  @ApiModelProperty(example = "yoursecretapikey", value = "Your secret API Key")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public Emailv1 emailDetails(EmailDetails emailDetails) {
    this.emailDetails = emailDetails;
    return this;
  }

   /**
   * Get emailDetails
   * @return emailDetails
  **/
  @ApiModelProperty(example = "null", value = "")
  public EmailDetails getEmailDetails() {
    return emailDetails;
  }

  public void setEmailDetails(EmailDetails emailDetails) {
    this.emailDetails = emailDetails;
  }

  public Emailv1 X_APIHEADER(List<String> X_APIHEADER) {
    this.X_APIHEADER = X_APIHEADER;
    return this;
  }

  public Emailv1 addXAPIHEADERItem(String X_APIHEADERItem) {
    this.X_APIHEADER.add(X_APIHEADERItem);
    return this;
  }

   /**
   * Get X_APIHEADER
   * @return X_APIHEADER
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getXAPIHEADER() {
    return X_APIHEADER;
  }

  public void setXAPIHEADER(List<String> X_APIHEADER) {
    this.X_APIHEADER = X_APIHEADER;
  }

  public Emailv1 settings(Settings settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @ApiModelProperty(example = "null", value = "")
  public Settings getSettings() {
    return settings;
  }

  public void setSettings(Settings settings) {
    this.settings = settings;
  }

  public Emailv1 recipients(List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public Emailv1 addRecipientsItem(String recipientsItem) {
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRecipients() {
    return recipients;
  }

  public void setRecipients(List<String> recipients) {
    this.recipients = recipients;
  }

  public Emailv1 attributes(Attributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Attributes getAttributes() {
    return attributes;
  }

  public void setAttributes(Attributes attributes) {
    this.attributes = attributes;
  }

  public Emailv1 files(Files files) {
    this.files = files;
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @ApiModelProperty(example = "null", value = "")
  public Files getFiles() {
    return files;
  }

  public void setFiles(Files files) {
    this.files = files;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emailv1 emailv1 = (Emailv1) o;
    return Objects.equals(this.apiKey, emailv1.apiKey) &&
        Objects.equals(this.emailDetails, emailv1.emailDetails) &&
        Objects.equals(this.X_APIHEADER, emailv1.X_APIHEADER) &&
        Objects.equals(this.settings, emailv1.settings) &&
        Objects.equals(this.recipients, emailv1.recipients) &&
        Objects.equals(this.attributes, emailv1.attributes) &&
        Objects.equals(this.files, emailv1.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, emailDetails, X_APIHEADER, settings, recipients, attributes, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emailv1 {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    emailDetails: ").append(toIndentedString(emailDetails)).append("\n");
    sb.append("    X_APIHEADER: ").append(toIndentedString(X_APIHEADER)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

