/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Files
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T12:18:50.368Z")
public class Files   {
  @SerializedName("example_attachment1.txt")
  private String exampleAttachment1Txt = null;

  @SerializedName("example_attachment2.txt")
  private String exampleAttachment2Txt = null;

  public Files exampleAttachment1Txt(String exampleAttachment1Txt) {
    this.exampleAttachment1Txt = exampleAttachment1Txt;
    return this;
  }

   /**
   * Get exampleAttachment1Txt
   * @return exampleAttachment1Txt
  **/
  @ApiModelProperty(example = "This is a test content of the attach text file 1", value = "")
  public String getExampleAttachment1Txt() {
    return exampleAttachment1Txt;
  }

  public void setExampleAttachment1Txt(String exampleAttachment1Txt) {
    this.exampleAttachment1Txt = exampleAttachment1Txt;
  }

  public Files exampleAttachment2Txt(String exampleAttachment2Txt) {
    this.exampleAttachment2Txt = exampleAttachment2Txt;
    return this;
  }

   /**
   * Get exampleAttachment2Txt
   * @return exampleAttachment2Txt
  **/
  @ApiModelProperty(example = "This is a test content of the attach text file 2", value = "")
  public String getExampleAttachment2Txt() {
    return exampleAttachment2Txt;
  }

  public void setExampleAttachment2Txt(String exampleAttachment2Txt) {
    this.exampleAttachment2Txt = exampleAttachment2Txt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Files files = (Files) o;
    return Objects.equals(this.exampleAttachment1Txt, files.exampleAttachment1Txt) &&
        Objects.equals(this.exampleAttachment2Txt, files.exampleAttachment2Txt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exampleAttachment1Txt, exampleAttachment2Txt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Files {\n");
    
    sb.append("    exampleAttachment1Txt: ").append(toIndentedString(exampleAttachment1Txt)).append("\n");
    sb.append("    exampleAttachment2Txt: ").append(toIndentedString(exampleAttachment2Txt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

