/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Settings
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T12:18:50.368Z")
public class Settings   {
  @SerializedName("footer")
  private Boolean footer = true;

  @SerializedName("clicktrack")
  private Boolean clicktrack = true;

  @SerializedName("opentrack")
  private Boolean opentrack = true;

  @SerializedName("unsubscribe")
  private Boolean unsubscribe = true;

  @SerializedName("bcc")
  private String bcc = null;

  @SerializedName("attachmentid")
  private String attachmentid = null;

  @SerializedName("template")
  private Integer template = null;

  public Settings footer(Boolean footer) {
    this.footer = footer;
    return this;
  }

   /**
   * Get footer
   * @return footer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getFooter() {
    return footer;
  }

  public void setFooter(Boolean footer) {
    this.footer = footer;
  }

  public Settings clicktrack(Boolean clicktrack) {
    this.clicktrack = clicktrack;
    return this;
  }

   /**
   * Get clicktrack
   * @return clicktrack
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getClicktrack() {
    return clicktrack;
  }

  public void setClicktrack(Boolean clicktrack) {
    this.clicktrack = clicktrack;
  }

  public Settings opentrack(Boolean opentrack) {
    this.opentrack = opentrack;
    return this;
  }

   /**
   * Get opentrack
   * @return opentrack
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOpentrack() {
    return opentrack;
  }

  public void setOpentrack(Boolean opentrack) {
    this.opentrack = opentrack;
  }

  public Settings unsubscribe(Boolean unsubscribe) {
    this.unsubscribe = unsubscribe;
    return this;
  }

   /**
   * Get unsubscribe
   * @return unsubscribe
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUnsubscribe() {
    return unsubscribe;
  }

  public void setUnsubscribe(Boolean unsubscribe) {
    this.unsubscribe = unsubscribe;
  }

  public Settings bcc(String bcc) {
    this.bcc = bcc;
    return this;
  }

   /**
   * Get bcc
   * @return bcc
  **/
  @ApiModelProperty(example = "bcc@example.com", value = "")
  public String getBcc() {
    return bcc;
  }

  public void setBcc(String bcc) {
    this.bcc = bcc;
  }

  public Settings attachmentid(String attachmentid) {
    this.attachmentid = attachmentid;
    return this;
  }

   /**
   * Get attachmentid
   * @return attachmentid
  **/
  @ApiModelProperty(example = "1,2,5", value = "")
  public String getAttachmentid() {
    return attachmentid;
  }

  public void setAttachmentid(String attachmentid) {
    this.attachmentid = attachmentid;
  }

  public Settings template(Integer template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTemplate() {
    return template;
  }

  public void setTemplate(Integer template) {
    this.template = template;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.footer, settings.footer) &&
        Objects.equals(this.clicktrack, settings.clicktrack) &&
        Objects.equals(this.opentrack, settings.opentrack) &&
        Objects.equals(this.unsubscribe, settings.unsubscribe) &&
        Objects.equals(this.bcc, settings.bcc) &&
        Objects.equals(this.attachmentid, settings.attachmentid) &&
        Objects.equals(this.template, settings.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(footer, clicktrack, opentrack, unsubscribe, bcc, attachmentid, template);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    clicktrack: ").append(toIndentedString(clicktrack)).append("\n");
    sb.append("    opentrack: ").append(toIndentedString(opentrack)).append("\n");
    sb.append("    unsubscribe: ").append(toIndentedString(unsubscribe)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    attachmentid: ").append(toIndentedString(attachmentid)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

