/**
 * Pepipost API v1.0
 * Pepipost API documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Emailv1;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailApi
 */
public class EmailApiTest {

    private final EmailApi api = new EmailApi();

    
    /**
     * 
     *
     * &#x60;Sending Mails&#x60; – This API is used for sending emails. Pepipost supports REST as well JSON formats for the input. This is JSON API. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiWebSendJsonPostTest() throws ApiException {
        Emailv1 data = null;
        // api.apiWebSendJsonPost(data);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * &#x60;Sending Mails&#x60; – This API is used for sending emails. Pepipost supports REST as well JSON formats for the input 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiWebSendRestGetTest() throws ApiException {
        String apiKey = null;
        String from = null;
        String subject = null;
        String content = null;
        String recipients = null;
        String fromname = null;
        String replytoid = null;
        Boolean footer = null;
        Integer template = null;
        String attachmentid = null;
        Boolean clicktrack = null;
        Boolean opentrack = null;
        String bcc = null;
        String ATT_NAME = null;
        String X_APIHEADER = null;
        String tags = null;
        // api.apiWebSendRestGet(apiKey, from, subject, content, recipients, fromname, replytoid, footer, template, attachmentid, clicktrack, opentrack, bcc, ATT_NAME, X_APIHEADER, tags);

        // TODO: test validations
    }
    
}
